# Generated by Django 5.1 on 2024-08-23 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='image',
        ),
    ]
