# Generated by Django 5.1 on 2024-08-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0002_remove_trainee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trainee/images/'),
        ),
    ]
